In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [7]:
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [5]:
y = np.zeros(5)
y

array([0., 0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [10]:
np.hstack((x,y))

array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [18]:
print ("Dimesion: ", x.ndim)
print ("shape: ", x.shape)
print ("size: ", x.size)
print ("content type: ", x.dtype)
print ("type: ", type(x))


Dimesion:  1
shape:  (5,)
size:  5
content type:  float64
type:  <class 'numpy.ndarray'>


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [23]:
w = np.array([[11, 12], [13, 14], [15, 16]])
w.shape

(3, 2)

## Q#6: Create z array contains the numbers from 1 to 3.

In [25]:
z = np.array([1, 2, 3])
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [41]:
newArray = np.hstack((z,w.ravel()))
newArray

array([ 1,  2,  3, 11, 12, 13, 14, 15, 16])

## Q#8: Print all elements of "newArray" using the loop.

In [42]:
for i in newArray :
    print(i)

1
2
3
11
12
13
14
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [43]:
np.flip(newArray)


array([16, 15, 14, 13, 12, 11,  3,  2,  1])

## Q#10: Decrement all elements of "newArray" with 1.

In [45]:
newArray -= 1
newArray

array([ 0,  1,  2, 10, 11, 12, 13, 14, 15])

## Q#11: Find smallest and biggest values in "newArray".

In [46]:
print("the smallest v is : ", newArray.min())
print("the biggest v is : ", newArray.max())

the smallest v is :  0
the biggest v is :  15


## Q#12: Print the first row of "newArray" using indexing.

In [47]:
newArray[0]

0

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [53]:
for i , j in enumerate(newArray) :
     if j == 12 :
        break
newArray[i]

12

In [54]:
newArray [5]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [56]:
for i , j in enumerate(newArray) :
     if j == 0 or j == 13 :
        print(f"the number {j} is in index {i}")

the number 0 is in index 0
the number 13 is in index 6


## Q#15: Change the shape of "newArray" to (9,1).

In [57]:
newArray.reshape(9,1)

array([[ 0],
       [ 1],
       [ 2],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,3).

In [58]:
newArray.reshape(3,3)

array([[ 0,  1,  2],
       [10, 11, 12],
       [13, 14, 15]])

# Well Done 🎉